// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olrjeneqkojowyyhqzln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9scmplbmVxa29qb3d5eWhxemxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzgwMzQsImV4cCI6MjA3MzA1NDAzNH0.oLjTYRY1ZKjHaKulXfFkRvt57sFs2K627tC4s2FelOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});